### PR TITLE
Update DynamicConfigFile.cs

### PR DESCRIPTION
**Pull request by Vlad-00003**
Added ability to convert lists and dictionaries that contain custom classes.

### CODE REVIEW

**Comment by lukespragg** [comment]
Could you provide an example of where this would be useful in a plugin?

**Comment by Vlad-00003** [comment]
? O_o
Like.... anywhere.

Let's say you have your own custom class called `Tree`:
```csharp
private class Tree
{
    public int LeafsCount;
}```

And you wanna store it in the config.
The code like this is going to work:
```csharp
var tree = new Tree();
Config["Tree class"] = tree;```
And this filed would be saved as the dictionarry.
But - if we would try to get it back - we would get Dictionarry<string,object> insted of our class...

So - the only way to do this now, is to create your own class for the config, and then write it as an object.
It is also possible to create your own way to handle the custom classes in the config on the plugin side - just store any of them as the Dictionarry<string,object>, but... Why doing so, if this can be handled by the oxide itself?

**Comment by lukespragg** [comment]
Thanks, was just looking for clarification.

**Comment by Vlad-00003** [comment]
@lukespragg, also - check the latest changes in the request. I think they might be usefull too.

**Comment by Vlad-00003** [comment]
Ok, that didn't work. Anyway - I've tried....

**Comment by Vlad-00003** [comment]
Wow. It's been a while. At least this one is closed, I guess ¯\_(ツ)_/¯

**Comment by lukespragg** [comment]
It was automatic. :P

I think this was sort of forgotten about.

**Comment by Vlad-00003** [comment]
Happens. 
I can't even think of all the things I've left behind for the same reason...

**Comment by Calytic** [comment]
Problem with Get<T> is that the function expects a generic return value but "null" is not a generic return value (unless the proper type constraints are specified).

Should be..
```
public T Get<T>(params string[] path)
{
    object val = Get(path);
    return val == null ? default : ConvertValue<T>(val);
}
```

Also, we don't want to simplify the config indexer because the behavior of "params" under the hood allocates an array in earlier versions of .NET.

I went ahead and ported this code over to uMod (with the necessary fixes). Thanks @Vlad-00003

**Pull request closed without merging**
